export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAIL = 'SEND_CONTACT_FAIL';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
